var Mock = require('mockjs')
var fs = require("fs")
var data = Mock.mock({
  //分类信息
  "categories":[
    {
      "id":1,
      "name":"首页",
      "categorie":[
        {
          "id":1,
          "img":"https://img.thebeastshop.com/apppictures/2017-11-03/dbbacff849f9ad49ee687ca5d083e679.jpg@0o_0l_750w_90q.jpg",
          "name":"新人专享",
          "title":"野兽小镇给新居民的新年礼物！",
          "text":"新人福利，注册即送价值￥360礼券，和野兽们一起欢庆圣诞吧！"
        },
        {
          "id":2,
          "name":"明星同款",
          "title":"狗年戴狗旺旺旺",
          "text":"狗年来临！2018你是哈士奇、柯基还是秋田？",
          "img":"https://img.thebeastshop.com/apppictures/2018-01-15/31d83fbc357b458f972ccffda28ac7b7.jpg@0o_0l_750w_90q.jpg",
        },
        {
          "id":3,
          "name":"家饰摆件",
          "title":"新年转运 | 用金才能多金",
          "text":"新年彩运滚滚来！",
          "img":"https://img.thebeastshop.com/apppictures/2018-01-12/ed11eeb570e2e022a12592300d891dde.png@0o_0l_750w_90q.png",
        },
        {
          "id":4,
          "name":"护肤美容",
          "title":"年会派对'美人计'",
          "text":"急救让你烦心的肌肤问题，光彩照人妥妥的。",
          "img":"https://img.thebeastshop.com/apppictures/2018-01-12/8a55bb07e43d7580a0e96342f243d511.jpg@90q.jpg",
        },
        {
          "id":5,
          "name":"头发护理",
          "title":"2018'头'等大事，解决你所有头发烦恼",
          "text":"针对不同女生的护发秘笈，褪色、脱发、干枯等问题通通搞定。",
          "img":"https://img.thebeastshop.com/apppictures/2018-01-05/c3b41d1ffeb73c892abe96bf31e8e95a.jpg@90q.jpg",
        },
        {
          "id":6,
          "name":"时髦零食",
          "title":"严冬请喝茶",
          "text":"来自巴黎的Mariage Freres,拥有多种美好味道，暖胃又暖心。",
          "img":"https://img.thebeastshop.com/apppictures/2018-01-12/bcfb1b1b992c2b7a92403727b3e5258.png@0o_0l_750w_90q.png",
        },
        {
          "id":7,
          "name":"花卉",
          "title":"一朵植物的更多可能",
          "text":"用植物装点墙壁吧,绿色清晰，将植物元素尽可能的融入日常生活。",
          "img":"https://img.thebeastshop.com/apppictures/2018-01-15/e6c20194d236a5fdc5a5779247d401c3.jpg@0o_0l_750w_90q.jpg",
        },
        {
          "id":8,
          "name":"编辑推荐"
        },
      ]
    },
    {
      "id":2,
      "name":"野兽家具廊",
      //判断是否展开下拉列表
      "Bol":false,
      "categorie":[
        {
          "id":1,
          "name":"家纺"
        },
        {
          "id":2,
          "name":"家饰"
        },
        {
          "id":3,
          "name":"餐厨"
        },
        {
          "id":4,
          "name":"进入店铺"
        },
      ]
    },
    {
      "id":3,
      "name":"野兽派花店",
      "Bol":false,
      "categorie":[
        {
          "id":1,
          "name":"鲜花"
        },
        {
          "id":2,
          "name":"永生花"
        },
        {
          "id":3,
          "name":"花器"
        },
        {
          "id":4,
          "name":"限量礼盒"
        },
        {
          "id":5,
          "name":"进入店铺"
        },
      ]
    },
    {
      "id":4,
      "name":"野兽小姐",
      "Bol":false,
      "categorie":[
        {
          "id":1,
          "name":"家居服"
        },
        {
          "id":2,
          "name":"高级珠宝"
        },
        {
          "id":3,
          "name":"时尚珠宝"
        },
        {
          "id":4,
          "name":"围巾"
        },
        {
          "id":5,
          "name":"其他配饰"
        },
        {
          "id":6,
          "name":"进入店铺"
        },
      ]
    },
    {
      "id":5,
      "name":"贵妇美容室",
      "Bol":false,
      "categorie":[
        {
          "id":1,
          "name":"个人护理"
        },
        {
          "id":2,
          "name":"护肤彩妆"
        },
        {
          "id":3,
          "name":"美容仪器"
        },
        {
          "id":4,
          "name":"蜡烛散香"
        },
        {
          "id":5,
          "name":"更多香氛"
        },
        {
          "id":6,
          "name":"贵妇礼盒"
        },
        {
          "id":7,
          "name":"进入店铺"
        },
      ]
    },
    {
      "id":6,
      "name":"新鲜上架"
    },
    {
      "id":7,
      "name":"海外直邮"
    },
    {
      "id":8,
      "name":"折扣优惠"
    },
    {
      "id":9,
      "name":"实体店"
    },
  ],
  //商品信息
  "products|1000":[
    {
      "id|+1":1,
      //大分类id
      "categoriesId|1-9":1,
      //小分类id
      "categorieId|1-8":1,
      //商品名
      "name":"@cword(3,5)",
      "names":"@last()",
      //价格
      "price|99-9999.2":10,
      //材质
      "texture":"@cword(4,6)",
      //尺寸
      "size|10-99":10,
      //产地
      "origin":"@cword(2,4)",
      //小图
      "img":"@image(292x304,@color)",
      //大图
      "imgs":"@image(375x391,@color)",
      //上架时间
      "time|20-50":10,
      //推荐理由
      "reason":"@cparagraph()",
      //品牌故事
      "story":"@cparagraph()"
    }
  ]
})

fs.writeFile("db.json",JSON.stringify(data,null,2),function(){
  console.log("文件写入成功")
})